# Generated by Django 5.2.4 on 2026-05-15 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "일반"),
                            ("NOTICE", "공지"),
                            ("MEETING", "회의"),
                            ("CAMP", "행사"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("is_all_day", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_at"],
                "indexes": [
                    models.Index(
                        fields=["start_at", "end_at"],
                        name="events_even_start_a_8d8d94_idx",
                    )
                ],
            },
        ),
    ]
