# Generated by Django 5.2.4 on 2026-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("ADMIN", "Admin")],
                default="USER",
                max_length=10,
            ),
        ),
    ]
