# Generated by Django 5.2.4
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(name="SurveyResponse"),
        migrations.DeleteModel(name="SurveyChoice"),
        migrations.DeleteModel(name="SurveyQuestion"),
        migrations.AddField(
            model_name="survey",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="survey",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="survey",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, db_index=True),
        ),
        migrations.RemoveField(model_name="survey", name="is_published"),
        migrations.RemoveField(model_name="survey", name="target_audience"),
        migrations.AlterField(
            model_name="survey",
            name="title",
            field=models.CharField(max_length=220),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=240)),
                ("question_type", models.CharField(max_length=12, choices=[("TEXT", "Text"), ("TEXTAREA", "Long text"), ("CHOICE", "Single choice"), ("MULTIPLE", "Multiple choice"), ("SCALE", "Scale 1-5")])),
                ("required", models.BooleanField(default=True)),
                ("options", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={"unique_together": {("survey", "respondent")}},
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="surveys.question",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="surveys.response",
                    ),
                ),
            ],
            options={"unique_together": {("response", "question")}},
        ),
    ]
